# Generated by Django 4.2.1 on 2023-05-28 18:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='course_offered',
            field=models.ManyToManyField(to='home.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000),
        ),
    ]
