# Generated by Django 4.2.1 on 2023-06-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog_testimonial_contact_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='course',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
