# Generated by Django 4.2.1 on 2023-06-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='front/images/logo/img.png', null=True, upload_to='courses/image/'),
        ),
    ]
